export const metadata = {
  title: "Privacy Policy | Dux Bowling",
  description: "Privacy Policy for Dux Bowling LLC",
};

export default function PrivacyPage() {
  return (
    <main style={{ maxWidth: "800px", margin: "0 auto", padding: "2rem" }}>
      <h1>Privacy Policy</h1>
      <p><em>Last updated: January 2026</em></p>

      <p>
        Dux Bowling LLC (“Dux Bowling,” “we,” “our,” or “us”) respects your privacy
        and is committed to protecting your personal information. This Privacy
        Policy explains how we collect, use, store, and share information when
        you use our website, services, and related products.
      </p>

      <h2>1. Information We Collect</h2>

      <h3>Information you provide directly</h3>
      <ul>
        <li>Email address</li>
        <li>Name or display name</li>
        <li>Account login credentials</li>
        <li>
          Bowling-related data you submit (scores, frames, pin states, lane
          identifiers)
        </li>
      </ul>

      <h3>Information collected automatically</h3>
      <ul>
        <li>IP address</li>
        <li>Browser type and device information</li>
        <li>Pages visited and usage data</li>
        <li>Cookies and session data for login and analytics</li>
      </ul>

      <h3>Future hardware integration</h3>
      <p>
        If you use Dux Bowling services connected to bowling lanes or pinsetting
        equipment, we may collect gameplay, scoring, and lane interaction data
        generated by those systems.
      </p>

      <h2>2. How We Use Your Information</h2>
      <ul>
        <li>Create and manage user accounts</li>
        <li>Provide scoring, tracking, and gameplay features</li>
        <li>Improve site performance and user experience</li>
        <li>Send service-related communications</li>
        <li>Support future lane and pinsetter integrations</li>
        <li>Maintain security and prevent misuse</li>
      </ul>

      <p>We do <strong>not</strong> sell your personal information.</p>

      <h2>3. Data Storage &amp; Security</h2>
      <p>
        Your data is stored using secure third-party hosting and infrastructure
        providers. We use reasonable administrative, technical, and physical
        safeguards to protect your information. However, no system can be
        guaranteed 100% secure.
      </p>

      <h2>4. Sharing of Information</h2>
      <p>We may share information with:</p>
      <ul>
        <li>Hosting and infrastructure providers</li>
        <li>Analytics services</li>
        <li>Email delivery services for account communications</li>
      </ul>
      <p>
        We only share information necessary to operate our services.
      </p>

      <h2>5. Cookies &amp; Tracking</h2>
      <p>
        We use cookies and similar technologies to maintain login sessions,
        analyze site usage, and improve performance. You can control cookies
        through your browser settings.
      </p>

      <h2>6. Data Retention</h2>
      <p>
        We retain your information for as long as your account is active or as
        needed to provide services. You may request deletion of your account and
        associated data by contacting us.
      </p>

      <h2>7. Your Rights</h2>
      <p>
        Depending on your location, you may have the right to access, correct,
        or delete your personal information. Requests can be sent to{" "}
        <a href="mailto:privacy@duxbowling.com">privacy@duxbowling.com</a>.
      </p>

      <h2>8. Children’s Privacy</h2>
      <p>
        Dux Bowling services are not intended for children under 13. We do not
        knowingly collect personal information from children.
      </p>

      <h2>9. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Updates will be
        posted on this page with a revised date.
      </p>

      <h2>10. Contact Us</h2>
      <p>
        Dux Bowling LLC<br />
        <a href="mailto:privacy@duxbowling.com">privacy@duxbowling.com</a>
      </p>
    </main>
  );
}